---
project_name: oreilly-trial
env:
  - CGO_ENABLED=0
  - GOFLAGS=-mod=vendor
  - GO111MODULE=auto
before:
  hooks:
    - go mod vendor
builds:
  - id: binary
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
    main: ./main.go
archives:
  - replacements:
      amd64: x86_64
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^build:'
      - '^Merge branch'
      - '^Merge pull request'
dockers:
  - image_templates:
      - "docker.io/bilalcaliskan/oreilly-trial:{{ .Tag }}"
      - "docker.io/bilalcaliskan/oreilly-trial:latest"
    goos: linux
    goarch: amd64
    use: docker
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
brews:
  - name: oreilly-trial
    tap:
      # The token determines the release type (Github/Gitlab).
      owner: bilalcaliskan
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    folder: Formula
    # Brew fails from multiple 32-bit arm versions.
    # Specify which version should be used.
    goarm: 6
    homepage: https://github.com/bilalcaliskan/oreilly-trial
    license: apache-2.0
    description: oreilly-trial creates a trial Oreilly account for 10 days
